### ISSUE TITLE
Finishing up TypeScript transition work

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-devp2p#52]
TODO List and discussion for finishing up on the TypeScript transition PR at https://github.com/ethereumjs/ethereumjs-devp2p/pull/51.

- [x] Updated TypeScript config on `ethereumjs-config` and/or in the repo
- [x] Test run on supported Node versions 8, 10, 11 (12 optional)
- [x] Integration test on [ethereumjs-client](https://github.com/ethereumjs/ethereumjs-client) repository, basic benchmarking (2-5 min run comparisons on different protocols)
- [x] Examples test run working confirmation
- [x] Update `README` (examples, URLs, method signatures)
- [x] Decision on TypeScript definition files (`definitions` folder), keep or not?
- [ ] [TODO] Other

**Comment by holgerd77** [comment]
Closed by #51 and subsequent work from @PhilippLgh
