### ISSUE TITLE
v3.0.0 Release Planning

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-devp2p#63]
The `v3.0.0` release for this library is imminent, introducing a `TypeScript` based version of the library and building upon the work from @dryajov done in https://github.com/ethereumjs/ethereumjs-devp2p/pull/56.

It is encouraged to test the current `master` branch of the library (this needs the bootnode update from the TODOs to work). If you have got comments on the release please drop here.

TODOs:

- [x] Release `v1.5.1` of the [common](https://github.com/ethereumjs/ethereumjs-vm/tree/master/packages/common) library on the VM monorepo side with the [updated bootnodes](https://github.com/ethereumjs/ethereumjs-vm/pull/718) and integrate here (via explicit PR separate from the release PR) //cc @evertonfraga 
- [x] Update [keccak](https://github.com/cryptocoinjs/keccak) dependency to `v3.0.0`
- [x] Move `ethereumjs-tx` dependency to `devDependencies` (used for examples)
- [x] Move `examples` out of the `src` directory
- [x] Eventually update `secp2561` dependency to `v4.0.0` (careful, breaking changes, see https://github.com/ethereumjs/ethereumjs-util/pull/228 for context, only if not causing too much side-hazzle)
- [x] Test, eventually fix and test the `npm pack` command to have a working release bundled

**Comment by holgerd77** [comment]
Hi @PhilippLgh, the `common` library [v1.5.1](https://github.com/ethereumjs/ethereumjs-vm/releases/tag/%40ethereumjs%2Fcommon%401.5.1) has now been released, can we continue with the release here? Can you also have a look into the other tow TODOs I added here? Thanks!

**Comment by PhilippLgh** [comment]
keccak update:
https://github.com/ethereumjs/ethereumjs-devp2p/pull/64

**Comment by PhilippLgh** [comment]
@holgerd77  regarding the secp256k1 update:
question is if it would make sense to bring in and use `ethereumjs-util` instead of directly working on `secp256k1`

**Comment by holgerd77** [comment]
Hmm, same question would go fork `keccak` as well and also for the `RLP` library. My tendency for now is to say that it's not worth it for the moment and rather lengthen things due to this a bit uncertain situation around the Util v7 release, see https://github.com/ethereumjs/ethereumjs-util/issues/250 (BN.js is not used here, nevertheless this might affect the validity of the Util v7 release itself).

Second against-argument would be that this also draws in unnecessary dependencies (like BN.js) not being used since this library works one level deeper down the stack.

So I would go for a plain `secp256k1` `v4.0.1` integration, both of these - also in the plain form - already help a lot making the installation process easier through the integrated precompiles.

**Comment by holgerd77** [comment]
Just had a look at the "run npm install" tab of the Node 10 (just as an example) [CI run](https://github.com/ethereumjs/ethereumjs-devp2p/pull/64/checks?check_run_id=663353610) for the `keccak` update PR.

The still executed `keccak` `v1.4.0` install brought me to the fact that there is actually an `ethereumjs-util` instance drawn in by the `ethereumjs-tx` dependency. This should actually not being in `dependencies` at all but moved to the `devDependencies`, since the library is just used by the examples. Have added this to the release preparation list.

I think we DO should also try to move out the `examples` directory of the `src` directory (or was this so super-difficult, can't exactly remember the reasoning here?). This is not done like this on any other of the libraries and just doesn't feel right.

Last but not least: the `npm pack` command is not doing useful things right now (at least for me locally), this likely needs a check before the release.

**Comment by PhilippLgh** [comment]
the reasoning behind moving `examples` into `src` is because they are source files (cannot be executed by nodejs).
if it is OK to always run them with `ts-node` we can move them one layer up. However, there might be differences in the execution environment which could effect e.g. the performance and reduce their usefulness for testing.

**Comment by holgerd77** [comment]
@PhilippLgh No, I think always run with `ts-node` is very much ok.

**Comment by PhilippLgh** [comment]
@holgerd77 made the suggested changes:
- remove examples: https://github.com/ethereumjs/ethereumjs-devp2p/pull/66
- update ethereumjs-common https://github.com/ethereumjs/ethereumjs-devp2p/pull/67
- move tx to devDependencies: https://github.com/ethereumjs/ethereumjs-devp2p/pull/65

**Comment by evertonfraga** [comment]
Regarding the `examples` code, one good practice is to have a specific package.json for modules that only that example needs.

The packages common to both, though, can be omitted from the `examples/package.json`, due to how recursive module resolution work in node. (1. `node_modules/xxx`, 2. `../node_modules/xxx`, 3. `../../node_modules/xxx`)

**Comment by holgerd77** [comment]
Closed by #71
