### ISSUE TITLE
Prepare for migration to the VM Monorepo

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-devp2p#86]
Those are some of the requirements to move this lib to the VM monorepo:
- [x] Migrate to TypeScript (rename `lib` to `src` in the process)
- [x] Update @ethereumjs/config to `v2.0.0`, see #91 
- [x] Remove coveralls configuration, replacing by Codecov
- [x] Remove github workflows, replacing by the ones in the monorepo format
- [x] Remove Babel configuration (to be replaced by Typescript build)
- [x] Unify Readme and package.json with the monorepo standards

**Comment by holgerd77** [comment]
Closed by https://github.com/ethereumjs/ethereumjs-vm/pull/971
